"""add email chains, chain scores, engagement metrics, configurable scoring

Revision ID: bc88dceb13af
Revises: a3f1b2c4d5e6
Create Date: 2026-03-06 14:07:46.906656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc88dceb13af'
down_revision: Union[str, None] = 'a3f1b2c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_subject', sa.String(), nullable=True),
    sa.Column('participants', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), nullable=True),
    sa.Column('email_count', sa.Integer(), nullable=True),
    sa.Column('outgoing_count', sa.Integer(), nullable=True),
    sa.Column('incoming_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chain_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('progression', sa.Integer(), nullable=True),
    sa.Column('responsiveness', sa.Integer(), nullable=True),
    sa.Column('persistence', sa.Integer(), nullable=True),
    sa.Column('conversation_quality', sa.Integer(), nullable=True),
    sa.Column('avg_response_hours', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('score_error', sa.Boolean(), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['email_chains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id')
    )
    op.add_column('emails', sa.Column('chain_id', sa.Integer(), nullable=True))
    op.add_column('emails', sa.Column('position_in_chain', sa.Integer(), nullable=True))
    op.add_column('emails', sa.Column('open_count', sa.Integer(), nullable=True))
    op.add_column('emails', sa.Column('click_count', sa.Integer(), nullable=True))
    op.add_column('emails', sa.Column('reply_count', sa.Integer(), nullable=True))
    op.add_column('emails', sa.Column('message_id', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('in_reply_to', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('thread_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'emails', 'email_chains', ['chain_id'], ['id'])
    op.add_column('settings', sa.Column('initial_email_prompt', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('chain_email_prompt', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('chain_evaluation_prompt', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('weight_value_proposition', sa.Float(), nullable=False))
    op.add_column('settings', sa.Column('weight_personalisation', sa.Float(), nullable=False))
    op.add_column('settings', sa.Column('weight_cta', sa.Float(), nullable=False))
    op.add_column('settings', sa.Column('weight_clarity', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'weight_clarity')
    op.drop_column('settings', 'weight_cta')
    op.drop_column('settings', 'weight_personalisation')
    op.drop_column('settings', 'weight_value_proposition')
    op.drop_column('settings', 'chain_evaluation_prompt')
    op.drop_column('settings', 'chain_email_prompt')
    op.drop_column('settings', 'initial_email_prompt')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'thread_id')
    op.drop_column('emails', 'in_reply_to')
    op.drop_column('emails', 'message_id')
    op.drop_column('emails', 'reply_count')
    op.drop_column('emails', 'click_count')
    op.drop_column('emails', 'open_count')
    op.drop_column('emails', 'position_in_chain')
    op.drop_column('emails', 'chain_id')
    op.drop_table('chain_scores')
    op.drop_table('email_chains')
    # ### end Alembic commands ###
